services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/app_db 
    depends_on:
      - db

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/app_db 
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db  
    volumes:
      - /Users/liviaalves/Workspace/dockerized-microservices-playground/db/init.sql:/docker-entrypoint-initdb.d/init.sql

